export interface IEnderecoConstructor {
  HISTORICO_ENDERECOS_ID: string
  CONTATOS_ID: string
  LOGR_TIPO: string
  LOGR_TITULO: string
  LOGR_NOME: string
  LOGR_NUMERO: string
  LOGR_COMPLEMENTO: string
  BAIRRO: string
  CIDADE: string
  UF: string
  CEP: string
  DT_INCLUSAO: string
  DT_ATUALIZACAO: string
  DT_INFORMACAO: string
  NSU: string
  ORIGEM_SERASA: string
  CNPJ_INFORMANTE: string
  BLOQUEADO: string
  DT_BLOQUEIO: string
  LOGON_BLOQUEIO: string
  DUPLICADO_MAIS_15_VEZES: string
  CLASSIFICACAO: string
  PRIORIDADE: string
  DT_METRALHADORA: string
  PUBLICO: string
  COMPARTILHADA: string
  ID_FINALIDADE: string
  de_MEIO_CAPTACAO_FORNECEDOR: string
  ID_LINK_FORNECEDOR: string
  de_FINALIDADE_FORNECEDOR: string
  dt_FINALIDADE_FORNECEDOR: string
  ENDERECO_PRINCIPAL: string
  COMUNICADO_INADIMPLENCIA: string
  LOGR_TIPO1: string
  LOGR_NOME1: string
  LOGR_NUMERO1: string
  LOGR_COMPLEMENTO1: string
  LOGR_BAIRRO1: string
  LOGR_CIDADE1: string
  LOGR_UF1: string
  LOGR_CEP1: string
  LOGR_LATITUDE1: string
  LOGR_LONGITUDE1: string
  LOGR_TIPO2: string
  LOGR_NOME2: string
  LOGR_NUMERO2: string
  LOGR_COMPLEMENTO2: string
  LOGR_BAIRRO2: string
  LOGR_CIDADE2: string
  LOGR_UF2: string
  LOGR_CEP2: string
  LOGR_LATITUDE2: string
  LOGR_LONGITUDE2: string
  LOGR_TIPO3: string
  LOGR_NOME3: string
  LOGR_NUMERO3: string
  LOGR_COMPLEMENTO3: string
  LOGR_BAIRRO3: string
  LOGR_CIDADE3: string
  LOGR_UF3: string
  LOGR_CEP3: string
  LOGR_LATITUDE3: string
  LOGR_LONGITUDE3: string
  MATCH_END: string
  ENDERECO: string
  CEP_NOTA: string
  CADASTRO_ID: string
  ORIGEM_SRS: string
  LATITUDE: string
  LONGITUDE: string
  STATUS_GEO: string
  COD_SETOR: string
  MATCH_GEO: string
  TIPO_ENDERECO_ID: string
  CARTA_DEVOLVIDA: string
  COMPARTILHADO: string,
  id_FINALIDADE: string
  ID_LINK: string
  COD_IBGE: string
}
